---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.9.1
      interval: 12h
      valuesFiles:
        - helmvalues.yaml
        - ../../vanguard/helmvalues.yaml
      ignoreMissingValuesFiles: true
