---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: acme@example.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
        webhook:
          groupName: acme.infomaniak.com
          solverName: infomaniak
          config:
            apiTokenSecretRef:
              name: infomaniak-api-credentials
              key: api-token
        selector:
          dnsZones:
            - "cyrilschreibernet.ch"
            - "the127001.ch"
            - "schreibernet.dev"
