---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-release
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: goauthentik/authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: authentik
      interval: 12h
