apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager/
  - certificates/schreibernet-dev-staging.yaml
  - issuers/letsencrypt-staging.yaml
  - issuers/secret-infomaniak-token.yaml
