---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-primary-deployment
  namespace: bind9
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: bind9
          volumeMounts:
            - name: bind9-config
              mountPath: /etc/bind
              readOnly: true
            - name: bind9-secrets
              mountPath: /etc/bind/secrets
              readOnly: true
      volumes:
        - name: bind9-config
          configMap:
            name: bind9-configmap
            items:
              - key: named-primary.conf
                path: named.conf
        - name: bind9-secrets
          secret:
            secretName: bind9-secrets
            items:
              - key: named.conf.key
                path: named.conf.key
