---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-deployment
  namespace: bind9
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: bind9-mount
          configMap:
            name: bind9-configmap
            items:
              - key: named.conf
                path: named.conf
              - key: schreibernet.dev.zone
                path: zones/schreibernet.dev.zone
