---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-zone-updater
  namespace: bind9
spec:
  template:
    spec:
      containers:
        - name: updater
          volumeMounts:
            - name: bind9-config
              mountPath: /etc/bind
              readOnly: true
            - name: bind9-secrets
              mountPath: /etc/bind/secrets
              readOnly: true
            - name: zones-configmap
              mountPath: /zones-git
              readOnly: true
            - name: zones-secrets
              mountPath: /zones-git/secrets
              readOnly: true
      volumes:
        - name: bind9-config
          configMap:
            name: bind9-configmap
            items:
              - key: rndc.conf
                path: rndc.conf
        - name: zones-configmap
          configMap:
            name: bind9-zones
            items:
              - key: schreibernet.dev.zone
                path: schreibernet.dev.zone
              - key: schreibernet.dev-ldap.zone
                path: schreibernet.dev-ldap.zone
              - key: 1.1.10.in-addr.arpa.zone
                path: 1.1.10.in-addr.arpa.zone
        - name: zones-secrets
          secret:
            secretName: bind9-secrets
            items:
              - key: named.conf.key
                path: named.conf.key
              - key: domainUUID
                path: schreibernet.dev-ldap-secret.zone
        - name: bind9-secrets
          secret:
            secretName: bind9-secrets
            items:
              - key: named.conf.key
                path: named.conf.key
