apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bind9
resources:
  - ../../base/bind9
  - secret-tsig.yaml
  - service.yaml
patches:
  - path: deployment.yaml
    target:
      name: bind9-deployment
      kind: Deployment
  - target:
      name: external-dns-deployment
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --rfc2136-zone=cyrilschreiber.ch
configMapGenerator:
  - name: bind9-configmap
    files:
      - config/named.conf
      - config/schreibernet.dev.zone
