apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/bind9
  - configmap.yaml
  - service.yaml
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
