---
apiVersion: v1
kind: Service
metadata:
  name: bind-service
  namespace: bind9
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dns.schreibernet.dev
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.1.142
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: bind9
