---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/infomaniak/cert-manager-webhook-infomaniak/releases/download/v0.3.1/rendered-manifest.yaml
  - certificates/schreibernet-dev-staging.yaml
  - issuers/letsencrypt-staging.yaml
  - issuers/secret-infomaniak-token.yaml
  - helmrelease.yaml
  - helmrepo.yaml
  - namespace.yaml
