---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 36.3.0
      interval: 12h

  values:
    deployment:
      enabled: true
      replicas: 3

    ports:
      web:
        redirections:
          to: websecure
          scheme: https
          permanent: true
      websecure:
        tls:
          enabled: true

    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik
      kubernetesIngress:
        enabled: true

    ingressClass:
      enabled: true

    rbac:
      enabled: true

    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.1.1.140
