---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - ../../base/authentik
  - certificate.yaml
patches:
  - path: helmrelease-values.yaml
    target:
      kind: HelmRelease
