apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: default-snapshot-cleanup
  namespace: longhorn-system
spec:
  name: default-snapshot-cleanup
  task: snapshot-cleanup
  concurrency: 1
  cron: 12 0 * * *
  groups:
    - default
