---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent
  namespace: portainer-agent
spec:
  type: LoadBalancer
  selector:
    app: portainer-agent
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001
status:
  loadBalancer:
    ingress:
      - ip: 10.1.1.141

---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent-headless
  namespace: portainer-agent
spec:
  clusterIP: None
  selector:
    app: portainer-agent
