---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  values:
    defaultSettings:
      allowCollectingLonghornUsageMetrics: false
    defaultBackupStore:
      backupTarget: nfs://10.1.1.20:/mnt/Vault/VaultData/Backups/4.App_Backups/Longhorn
    longhornUI:
      replicas: 1
    ingress:
      enabled: false
    persistence:
      defaultDataLocality: "best-effort"
