apiVersion: v1
data:
  named.conf: |
    acl internal {
        10.1.1.0/24;
        10.1.2.0/24;
        192.168.1.0/24;
        192.168.8.0/24;
    };

    options {
        forwarders {
            10.1.1.51;
            10.1.1.52;
            192.168.1.13;
        }
        allow-query { internal; };
        dnssec-validation auto;
    };

    zone "schreibernet.dev" {
        type master;
        file "/etc/bind/zones/schreibernet.dev.zone";
    };
  schreibernet.dev.zone: >
    $TTL 86400


    ; Dont forget to increment the serial number after making changes!


    $ORIGIN schreibernet.dev.

    @                               IN      SOA     ns.schreibernet.dev. admin.schreibernet.dev. (
                                                        2025073000 ; serial
                                                        12h        ; refresh
                                                        15m        ; retry
                                                        3w         ; expire
                                                        86400      ; minimum
                                                    )
    @                               IN      NS      ns.schreibernet.dev.

    ns                              IN      A       10.1.1.142


    ; -- A records for hosts in the network --


    mercury-fs-01                   IN      A       10.1.1.20

    kraken-dh-01                    IN      A       10.1.1.21
kind: ConfigMap
metadata:
  name: bind9-configmap
  namespace: bind9
