---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-deployment
  namespace: bind9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
        - name: bind9
          image: internetsystemsconsortium/bind9:9.21
          imagePullPolicy: Always
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          volumeMounts:
            - name: bind9-mount
              mountPath: /etc/bind
