---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-deployment
  namespace: bind9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
        - name: bind9
          image: internetsystemsconsortium/bind9:9.20
          imagePullPolicy: Always
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          volumeMounts:
            - name: bind9-data
              mountPath: /var/cache/bind
              readOnly: false

      volumes:
        - name: bind9-data
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-deployment
  namespace: bind9
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.18.0
          imagePullPolicy: Always
          args:
            - --registry=txt
            - --txt-prefix=external-dns-
            - --txt-owner-id=k8s
            - --provider=rfc2136
            - --rfc2136-host=bind-service.bind9.svc.cluster.local
            - --rfc2136-port=53
            - --rfc2136-zone=schreibernet.dev
            - --rfc2136-tsig-secret-alg=hmac-sha256
            - --rfc2136-tsig-keyname=tsig-key
            - --rfc2136-tsig-axfr
            - --source=traefik-proxy
            - --traefik-disable-legacy
            - --log-level=debug
          env:
            - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
              valueFrom:
                secretKeyRef:
                  name: bind9-key-secret
                  key: tsig-key
