---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind9-zone-pvc
  namespace: bind9
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
