---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind9-journals-pvc
  namespace: bind9
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
