apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-zone-updater
  namespace: bind9
spec:
  selector:
    matchLabels:
      app: zone-updater
  template:
    metadata:
      labels:
        app: zone-updater
    spec:
      containers:
        - name: updater
          image: internetsystemsconsortium/bind9:9.20
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              echo "Zone update started at $(date)"

              # Get servers addresses
              primaryServer=$(nslookup bind9-primary-headless | grep Address | awk '{print $2}' | sed '1d')
              secondaryServers=$(nslookup bind9-secondary-headless | grep Address | awk '{print $2}' | sed '1d')

              echo "Freezing zones"
              rndc -s $primaryServer freeze

              echo "Copying files"
              cp -f /zones-git/*.zone /persistent
              cp -f /zones-git/secrets/*.zone /persistent

              echo "Updating serials"
              for zoneFile in /persistent/*.zone; do
                echo "Updating serial in $zoneFile"
                # Update serial if SOA record exists
                if grep "; serial" "$zoneFile"; then
                  echo "Found serial on a separate line"
                  echo "Updating serial in $zoneFile"
                  serial=$(grep "; serial" "$zoneFile" | awk '{print $1}')
                  newSerial=$(date +%s)
                  sed -i "s/$serial ; serial/$newSerial ; serial/" "$zoneFile"
                elif grep -q "SOA" "$zoneFile"; then
                  echo "Found inline serial"
                  serial=$(grep "SOA" "$zoneFile" | awk '{print $6}')
                  newSerial=$(date +%s)
                  sed -i "s/\(SOA.*\) $serial/\1 $newSerial/" "$zoneFile"
                else
                  echo "No serial found"
                fi
              done

              echo "Thawing zones"
              rndc -s $primaryServer thaw

              echo "Zone update completed at $(date)"

              # Sleep to wait for primary to restart
              sleep 30

              for ip in $secondaryServers; do
                echo "Reloading secondary server: $ip"
                rndc -s $ip reload
              done

              echo "The end..."
              while true; do
              sleep 3600
              done
          volumeMounts:
            - name: bind9-data
              mountPath: /persistent
      volumes:
        - name: bind9-data
          persistentVolumeClaim:
            claimName: bind9-zone-pvc
