---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent
  namespace: portainer-agent
spec:
  type: LoadBalancer
  selector:
    app: portainer-agent
  loadBalancerIP: 10.1.1.141
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent-headless
  namespace: portainer-agent
spec:
  clusterIP: None
  selector:
    app: portainer-agent
